#!/bin/bash

echo -e "\033[33mcleaning up datasurf builds...\033[0m"

if [[ -d ./bin/ ]]
then
    rm ./bin/ -rf
fi

for obj in *.o
do
    if [[ ! -f $obj ]]
    then
        continue;
    fi

    rm $obj
done

for out in callgrind.*
do
    if [[ ! -f $out ]]
    then
        continue;
    fi

    rm $out
done

echo -e "\033[32mcleaned datasurf!\n\033[0m"
